#ifndef _HARDWARE_H_
#define _HARDWARE_H_

// Peripheral pin definitions
// PWM
#define HARDWARE_PIN_PWM  PIO0_8
// I2C
#define HARDWARE_PIN_SCL  PIO0_4
#define HARDWARE_PIN_SDA  PIO0_5
// SPI
#define HARDWARE_PIN_SSEL PIO0_2
#define HARDWARE_PIN_SCK  PIO0_6
#define HARDWARE_PIN_MISO PIO0_8
#define HARDWARE_PIN_MOSI PIO0_9
// UART
#define HARDWARE_PIN_RXD  PIO1_6
#define HARDWARE_PIN_TXD  PIO1_7

#endif
